train_gens = {"n_parity": 5,
              "n_parity_only_n": 5000,
                   "simple_alu": 10000,
                   "maze_with_stepping_stones": 4000,
                   "locomotion_with_obstacles": 1000,
                   "locomotion": 2000,
                   "deceptive_maze_easy": 100,
                   "Acrobot-v1": 1000,
                   "MountainCar-v0": 2000,
                   "MountainCarContinuous-v0": 2000,
                   "CartPole-v1": 4000,
                   "Breakout-MinAtar": 5000,
                   "Freeway-MinAtar": 5000,
                   "SpaceInvaders-MinAtar": 5000,
                   }



hyperparams = {
    "n_parity": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "n_parity_only_n": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
   "simple_alu": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "maze_with_stepping_stones": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "locomotion_with_obstacles": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "locomotion": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "deceptive_maze_easy": { "max_hidden_neurons": 24,
                     "discrete_weights": False,
                 },
    "Acrobot-v1": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "MountainCar-v0": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "MountainCarContinuous-v0": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "CartPole-v1": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "Breakout-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "Freeway-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
    "SpaceInvaders-MinAtar": { "max_hidden_neurons": 24,
                    "discrete_weights": False,
                },
}


