

# how many timesteps to run PPO in each environment
default_num_timesteps = {
                         "n_parity": 150_000_000,
                         "n_parity_singletask": 150_000_000,
                         "stepping_gates": 450_000_000,
    "stepping_gates_all_tasks": 450_000_000,
"LunarLander-v2": 450_000_000,
    "foraging_with_sensors": 500_000,
                         "ant": 150_000_000,
                         "2d_nav_switching": 850_000_000,
                         "random_leg_ant": 150_000_000,
"locomotion_with_obstacles": 750_000_000,
#"locomotion": 50_000_000,
"locomotion": 50_000_000,
"halfcheetah": 50_000_000,

"maze_with_stepping_stones_big": 50_000_000,
"maze_with_stepping_stones_small": 550_000_000,
"maze_with_stepping_stones_small_conditioned": 50_000_000,

"deceptive_maze": 50_000_000,
"deceptive_maze_easy": 150_000_000,

    "CartPole-v1": 50_000,
    "Acrobot-v1": 100_000,
    "2d_navigation": 500_000
}





gen_hyperparams = {
    "n_parity": {"reward_scaling": 1,
                         "unroll_length": 1,
                         "num_updates_per_batch": 4,
                         "discounting": 1.0,
                         "learning_rate": 3e-4,
                         "num_minibatches": 32,
                         "normalize_observations": False,
                         "num_envs": 4096,
                         "num_evals": 50,

                         "batch_size": 2048,
                         "entropy_cost": 1e-2,
                         "action_repeat": 1,
                         },

    "n_parity_singletask": {"reward_scaling": 1,
                 "unroll_length": 1,
                 "num_updates_per_batch": 4,
                 "discounting": 1.0,
                 "learning_rate": 3e-4,
                 "num_minibatches": 32,
                 "normalize_observations": False,
                 "num_envs": 4096,
                 "num_evals": 50,
                 "batch_size": 2048,
                 "entropy_cost": 1e-2,
                 "action_repeat": 1,
                 },
    "stepping_gates": {"reward_scaling": 1,
                 "unroll_length": 1,
                 "num_updates_per_batch": 4,
                 "discounting": 1.0,
                 "learning_rate": 3e-4,
                 "num_minibatches": 32,
                 "normalize_observations": False,
                 "num_envs": 4096,
                 "num_evals": 50,
                 "batch_size": 2048,
                 "entropy_cost": 1e-2,
                 "action_repeat": 1,
                 },
    "stepping_gates_all_tasks": {"reward_scaling": 1,
                       "unroll_length": 1,
                       "num_updates_per_batch": 4,
                       "discounting": 1.0,
                       "learning_rate": 3e-4,
                       "num_minibatches": 32,
                       "normalize_observations": False,
                       "num_envs": 4096,
                       "num_evals": 50,
                       "batch_size": 2048,
                       "entropy_cost": 1e-2,
                       "action_repeat": 1,
                       },
    ("ant"): {"reward_scaling": 10,
              "unroll_length": 5,
              "num_updates_per_batch": 4,
              "discounting": 0.97,
              "learning_rate": 3e-4,
              "num_minibatches": 32,
              "normalize_observations": True,
              "num_envs": 4096,
              "num_evals": 10,
              "batch_size": 2048,
              "entropy_cost": 1e-2,
              "action_repeat": 1,
              "episode_length": 1000
              },
    ("random_leg_ant"): {"reward_scaling": 10,
              "unroll_length": 5,
              "num_updates_per_batch": 4,
              "discounting": 0.97,
              "learning_rate": 3e-4,
              "num_minibatches": 32,
              "normalize_observations": True,
              "num_envs": 4096,
              "num_evals": 10,
              "batch_size": 2048,
              "entropy_cost": 1e-2,
              "action_repeat": 1,
              "episode_length": 1000
              },
    ("foraging_with_sensors"): {"reward_scaling": 10,
              "unroll_length": 5,
              "num_updates_per_batch": 4,
              "discounting": 0.97,
              "learning_rate": 3e-4,
              "num_minibatches": 32,
              "normalize_observations": True,
              "num_envs": 4096,
              "num_evals": 10,
              "batch_size": 2048,
              "entropy_cost": 1e-2,
              "action_repeat": 1,
              },
    ("2d_nav_switching"): {"reward_scaling": 10,
                                "unroll_length": 5,
                                "num_updates_per_batch": 4,
                                "discounting": 0.97,
                                "learning_rate": 3e-4,
                                "num_minibatches": 32,
                                "normalize_observations": True,
                                "num_envs": 4096,
                                "num_evals": 10,
                                "batch_size": 2048,
                                "entropy_cost": 1e-2,
                                "action_repeat": 1,
                           "episode_length": 100
                                },
    ("2d_navigation"): {"reward_scaling": 10,
                           "unroll_length": 5,
                           "num_updates_per_batch": 4,
                           "discounting": 0.97,
                           "learning_rate": 3e-4,
                           "num_minibatches": 32,
                           "normalize_observations": True,
                           "num_envs": 4096,
                           "num_evals": 10,
                           "batch_size": 2048,
                           "entropy_cost": 1e-2,
                           "action_repeat": 1,
                           "episode_length": 100
                           },
    "LunarLander-v2": {"reward_scaling": 1,
                 "unroll_length": 1,
                 "num_updates_per_batch": 4,
                 "discounting": 1.0,
                 "learning_rate": 3e-4,
                 "num_minibatches": 32,
                 "normalize_observations": False,
                 "num_envs": 4096,
                 "num_evals": 50,

                 "batch_size": 2048,
                 "entropy_cost": 1e-2,
                 "action_repeat": 1,
                 },
    "CartPole-v1": {"reward_scaling": 1,
                       "unroll_length": 1,
                       "num_updates_per_batch": 4,
                       "discounting": 1.0,
                       "learning_rate": 3e-4,
                       "num_minibatches": 32,
                       "normalize_observations": False,
                       "num_envs": 4096,
                       "num_evals": 50,

                       "batch_size": 2048,
                       "entropy_cost": 1e-2,
                       "action_repeat": 1,
                       },
    "Acrobot-v1": {"reward_scaling": 1,
                    "unroll_length": 1,
                    "num_updates_per_batch": 4,
                    "discounting": 1.0,
                    "learning_rate": 3e-4,
                    "num_minibatches": 32,
                    "normalize_observations": False,
                    "num_envs": 4096,
                    "num_evals": 50,

                    "batch_size": 2048,
                    "entropy_cost": 1e-2,
                    "action_repeat": 1,
                    },
    "maze_with_stepping_stones_small": {"reward_scaling": 10,
                   "unroll_length": 5,
                   "num_updates_per_batch": 4,
                   "discounting": 0.97,
                   "learning_rate": 3e-4,
                   "num_minibatches": 32,
                   "normalize_observations": True,
                   "num_envs": 4096,
                   "num_evals": 10,
                   "batch_size": 2048,
                   "entropy_cost": 1e-2,
                   "action_repeat": 1,
                   },
    "maze_with_stepping_stones_small_conditioned": {"reward_scaling": 10,
                                        "unroll_length": 5,
                                        "num_updates_per_batch": 4,
                                        "discounting": 0.97,
                                        "learning_rate": 3e-4,
                                        "num_minibatches": 32,
                                        "normalize_observations": True,
                                        "num_envs": 4096,
                                        "num_evals": 10,
                                        "batch_size": 2048,
                                        "entropy_cost": 1e-2,
                                        "action_repeat": 1,
                                        },
    "maze_with_stepping_stones_big": {"reward_scaling": 10,
                                        "unroll_length": 5,
                                        "num_updates_per_batch": 4,
                                        "discounting": 0.97,
                                        "learning_rate": 3e-4,
                                        "num_minibatches": 32,
                                        "normalize_observations": True,
                                        "num_envs": 4096,
                                        "num_evals": 10,
                                        "batch_size": 2048,
                                        "entropy_cost": 1e-2,
                                        "action_repeat": 1,
                                        },

    "deceptive_maze": {"reward_scaling": 10,
                                  "unroll_length": 5,
                                  "num_updates_per_batch": 4,
                                  "discounting": 0.97,
                                  "learning_rate": 3e-4,
                                  "num_minibatches": 32,
                                  "normalize_observations": True,
                                  "num_envs": 4096,
                                  "num_evals": 10,
                                  "batch_size": 2048,
                                  "entropy_cost": 1e-2,
                                  "action_repeat": 1,
                                  },
    "locomotion_with_obstacles": {"reward_scaling": 10,
                                  "unroll_length": 5,
                                  "num_updates_per_batch": 4,
                                  "discounting": 0.97,
                                  "learning_rate": 3e-4,
                                  "num_minibatches": 32,
                                  "normalize_observations": True,
                                  "num_envs": 4096,
                                  "num_evals": 10,
                                  "batch_size": 2048,
                                  "entropy_cost": 1e-2,
                                  "action_repeat": 1,
                                  },

    "locomotion": {"reward_scaling": 10,
                                  "unroll_length": 5,
                                  "num_updates_per_batch": 4,
                                  "discounting": 0.97,
                                  "learning_rate": 3e-4,
                                  "num_minibatches": 32,
                                  "normalize_observations": True,
                                  "num_envs": 4096,
                                  "num_evals": 10,
                                  "batch_size": 2048,
                                  "entropy_cost": 1e-2,
                                  "action_repeat": 1,
                                  },
    "halfcheetah": {"reward_scaling": 10,
                   "unroll_length": 5,
                   "num_updates_per_batch": 4,
                   "discounting": 0.97,
                   "learning_rate": 3e-4,
                   "num_minibatches": 32,
                   "normalize_observations": True,
                   "num_envs": 4096,
                   "num_evals": 10,
                   "batch_size": 2048,
                   "entropy_cost": 1e-2,
                   "action_repeat": 1,
                   },
    "deceptive_maze_easy": {"reward_scaling": 10,
                   "unroll_length": 5,
                   "num_updates_per_batch": 4,
                   "discounting": 0.97,
                   "learning_rate": 3e-4,
                   "num_minibatches": 32,
                   "normalize_observations": True,
                   "num_envs": 4096,
                   "num_evals": 10,
                   "batch_size": 2048,
                   "entropy_cost": 1e-2,
                   "action_repeat": 1,
                   },



}
